migrated from build.sh to prepare

diff --git a/profiles/default/prepare b/profiles/default/prepare
--- a/profiles/default/prepare
+++ b/profiles/default/prepare
@@ -3,6 +3,15 @@ set -e
 
 find /var/db/repos/localrepo -name '*.ebuild' -type f -exec ebuild {} manifest \;
 
+GENPACK_PROGS_DIR=/var/cache/repos/genpack-progs
+
+if [ -d $GENPACK_PROGS_DIR/.git ]; then
+        git -C $GENPACK_PROGS_DIR pull || echo "Failed accessing git. Proceedeng with present source..."
+else
+        git clone https://github.com/wbrxcorp/genpack-progs.git /var/cache/repos/genpack-progs
+fi
+(cd $GENPACK_PROGS_DIR && make && make install)
+
 build-kernel --config /kernel-config.`uname -m`
 
 emerge -uDN -bk --binpkg-respect-use=y --exclude='sys-kernel/*' world @all
