use genpack-overlay

diff --git a/profiles/stub/prepare b/profiles/stub/prepare
--- a/profiles/stub/prepare
+++ b/profiles/stub/prepare
@@ -1,14 +1,15 @@
 #!/bin/sh
 set -e
 
-GENPACK_PROGS_DIR=/var/cache/repos/genpack-progs
+GENPACK_OVERLAY=/var/cache/repos/genpack-overlay
 
-if [ -d $GENPACK_PROGS_DIR/.git ]; then
-        git -C $GENPACK_PROGS_DIR pull || echo "Failed accessing git. Proceedeng with present source..."
+if [ -d $GENPACK_OVERLAY/.git ]; then
+        git -C $GENPACK_OVERLAY pull || echo "Failed accessing git. Proceedeng with present source..."
 else
-        git clone https://github.com/wbrxcorp/genpack-progs.git /var/cache/repos/genpack-progs
+        git clone https://github.com/wbrxcorp/genpack-overlay.git $GENPACK_OVERLAY
+	mkdir -p /etc/portage/repos.conf
+	echo -e '[genpack-overlay]\nlocation=/var/cache/repos/genpack-overlay' > /etc/portage/repos.conf/genpack-overlay.conf
 fi
-(cd $GENPACK_PROGS_DIR && make && make install)
 
 # ensure there kernel configs
 # CONFIG_DEFAULT_INIT="/sbin/overlay-init"
